### ISSUE TITLE
Typo in "Moving files and folders within storage "

### ISSUE THREAD

**Issue by daria-moskovskykh** [neuro-inc/platform-docs#2]
Moving files and folders within storage 
https://docs.neu.ro/core/storage#moving-files-and-folders-within-storage

> To move a folder and its contents from storage folder to another, use the command: `neuro mv -T storage:nero-assistant/ModelCode storage:neuro-tutorial/SampleCode`
> This command **copies** the folder `ModelCode` and all its contents from the `nero-assistant` storage folder to the` neuro-tutorial `storage folder and renames the folder to `SampleCode`.

Should be "moves" instead of "copies".

Screenshot https://take.ms/8RVes

**Comment by jane-gorlova** [comment]
Fixed, in production
![image](https://user-images.githubusercontent.com/76050922/169974151-2fff9759-ab50-4ac3-b793-5bb659abf7b7.png)
