### ISSUE TITLE
Typo in "How do I use storage folders in jobs?"

### ISSUE THREAD

**Issue by daria-moskovskykh** [neuro-inc/platform-docs#3]
How do I use storage folders in jobs?
https://docs.neu.ro/core/storage#how-do-i-use-storage-folders-in-jobs

> To use a volume when running a job, you must mount the data from the storage to the container. Optionally, you can mount multiple volumes into the container.
> To mount a container, use the `--mount` parameter in the run command. For example: 
> `neuro run --name job303 --volume storage:nero-assistant/ModelCode:/code:rw --preset cpu-small ubuntu cat /code/train.py`

Should be `--volume parameter` instead of `--mount` parameter.

Screenshot https://take.ms/UEejz

**Comment by YevheniiSemendiak** [comment]
Resolved
