### ISSUE TITLE
Invalid links to run the ML Recipes

### ISSUE THREAD

**Issue by daria-moskovskykh** [neuro-inc/platform-docs#4]
Invalid links to run the ML Recipes. https://docs.neu.ro/web/ml-recipes

E.g., https://docs.neu.ro/cookbook/object-detection "Run on Neu.ro" link leads to `neuro-ai-public` cluster https://apps.neu.ro/ml-recipes/object-detection - `Failed to run an app: Cluster neuro-ai-public doesn't exist in a list of available clusters ['neuro-public']. Please logout and login again.`

Video https://jmp.sh/6JhhWgf

**Comment by YevheniiSemendiak** [comment]
we removed this page
